name: tazkir_app
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  bloc: ^8.1.2
  device_preview: ^1.1.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  modal_progress_hud_nsn: ^0.4.0
  rename: ^2.1.1

dev_dependencies:
  build_runner: ^2.3.2
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.0

flutter:
  uses-material-design: true

assets:
  fonts:
    - family: Poppins
      fonts:
        - asset: assets\fonts\Poppins-Regular.ttf
